doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '8.0.33'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        # https://symfony.com/doc/current/messenger.html#doctrine-transport
        schema_filter: '~^(?!messenger_messages)~'
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                connection: default
                mappings:
                    Frontend:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Frontend/Domain/Entity'
                        prefix: 'App\Frontend\Domain\Entity'
                        alias: Frontend
                    User:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/User/Domain/Entity'
                        prefix: 'App\User\Domain\Entity'
                        alias: User
                    Blog:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Blog/Domain/Entity'
                        prefix: 'App\Blog\Domain\Entity'
                        alias: Blog
                    Task:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Task/Domain/Entity'
                        prefix: 'App\Task\Domain\Entity'
                        alias: Task
                    Resume:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Resume/Domain/Entity'
                        prefix: 'App\Resume\Domain\Entity'
                        alias: Resume
                    Quiz:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Quiz/Domain/Entity'
                        prefix: 'App\Quiz\Domain\Entity'
                        alias: Quiz
                    Announce:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Announce/Domain/Entity'
                        prefix: 'App\Announce\Domain\Entity'
                        alias: Announce
                    Log:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Log/Domain/Entity'
                        prefix: 'App\Log\Domain\Entity'
                        alias: Log
