homepage:
    path: /{_locale}
    controller: App\Frontend\Transport\Controller\HomeController::index
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: home/index.html.twig
        _locale: '%locale%'


frontend-controllers:
    resource:
        path: '../src/Frontend/Transport/Controller/'
        namespace: App\Frontend\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

user-controllers:
    resource:
        path: '../src/User/Transport/Controller/'
        namespace: App\User\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'


task-controllers:
    resource:
        path: '../src/Task/Transport/Controller/'
        namespace: App\Task\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'


blog-controllers:
    resource:
        path: '../src/Blog/Transport/Controller/'
        namespace: App\Blog\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

quiz-controllers:
    resource:
        path: '../src/Quiz/Transport/Controller/'
        namespace: App\Quiz\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

resume-controllers:
    resource:
        path: '../src/Resume/Transport/Controller/'
        namespace: App\Resume\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

announce-controllers:
    resource:
        path: '../src/Announce/Transport/Controller/'
        namespace: App\Announce\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
