homepage:
    path: /{_locale}
    controller: App\Frontend\Transport\Controller\HomeController::index
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: home/index.html.twig
        _locale: '%locale%'


frontend-controllers:
    resource:
        path: '../src/Frontend/Transport/Controller/'
        namespace: App\Frontend\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

admin-controllers:
    resource:
        path: '../src/Admin/Transport/Controller/'
        namespace: App\Admin\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

user-controllers:
    resource:
        path: '../src/User/Transport/Controller/'
        namespace: App\User\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'


crm-controllers:
    resource:
        path: '../src/Crm/Transport/Controller/'
        namespace: App\Crm\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'


blog-controllers:
    resource:
        path: '../src/Blog/Transport/Controller/'
        namespace: App\Blog\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

quiz-controllers:
    resource:
        path: '../src/Quiz/Transport/Controller/'
        namespace: App\Quiz\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

resume-controllers:
    resource:
        path: '../src/Resume/Transport/Controller/'
        namespace: App\Resume\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

announce-controllers:
    resource:
        path: '../src/Announce/Transport/Controller/'
        namespace: App\Announce\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

ecommerce-controllers:
    resource:
        path: '../src/Ecommerce/Transport/Controller/'
        namespace: App\Ecommerce\Transport\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

api.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

api:
    resource: ../src/Crm/Application/API/
    type: annotation
    prefix: /api

auth:
    resource: ../src/Crm/Transport/Controller/Auth/
    type: annotation
    prefix: /auth

security:
    resource: ../src/Crm/Transport/Controller/Security/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

kernel:
    resource: ../src/Kernel.php
    type: annotation

home:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: homepage
        permanent: true

homeLocale:
    path: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        _locale: '%locale%'
        route: homepage
        permanent: true

2fa_login:
    path: /{_locale}/auth/2fa
    defaults:
        _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
    path: /{_locale}/auth/2fa_check
